export enum NavigationSections {
    main = 'main',
    payments = 'payments',
    paymentsAnalytics = 'payments_analytics',
    paymentsOperations = 'payments_operations',
    paymentsPayouts = 'payments_payouts',
    paymentsReports = 'payments_reports',
    paymentsIntegrations = 'payments_integrations',
    wallets = 'wallets',
    walletsWallet = 'wallets_wallet',
    walletsDeposits = 'wallets_deposits',
    walletsWithdrawals = 'wallets_withdrawals',
    walletsReports = 'wallets_reports',
    walletsIntegrations = 'wallets_integrations',
    claims = 'claims',
}
