export enum RoleAccessName {
    Payments = 'payments',
    ViewAnalytics = 'viewAnalytics',
    ViewInvoices = 'viewInvoices',
    ViewPayments = 'viewPayments',
    ViewRefunds = 'viewRefunds',
    ViewPayouts = 'viewPayouts',
    ViewApiKey = 'viewApiKey',
    ManageReports = 'manageReports',
    ManageWebhooks = 'manageWebhooks',
    CreateInvoice = 'createInvoice',
    CreatePaymentLink = 'createPaymentLink',
    CreateRefund = 'createRefund',
    Wallets = 'wallets',
    Claims = 'claims',
    ManageOrganizations = 'manageOrganizations',
}
